### ISSUE TITLE
Elastcon parsing error

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/pycrystal#2]
```
/root/.aiida/repository-default/repository/node/39/69/1198-d9f2-48df-815a-3a85a640a599/path/_scheduler-stderr.txt unexpected CRYSTOUT parser error in /root/.aiida/repository-default/repository/node/39/69/1198-d9f2-48df-815a-3a85a640a599/path/_scheduler-stderr.txt:
 Traceback (most recent call last):
  File "/root/tilde/tilde/core/api.py", line 280, in _parse
    for calc in self.Parsers[parser_name].iparse(parsable):
  File "/root/tilde/tilde/parsers/__init__.py", line 117, in iparse
    return [cls(filename)]
  File "/root/tilde/tilde/parsers/CRYSTAL/CRYSTAL.py", line 17, in __init__
    result = _CRYSTOUT(filename)
  File "/usr/local/lib/python3.5/dist-packages/pycrystal/output.py", line 283, in __init__
    self.info['elastic']['elastic_moduli'] = self.get_elastic('elastic_moduli')
  File "/usr/local/lib/python3.5/dist-packages/pycrystal/output.py", line 785, in get_elastic
    constants[-1].append(float(ec))
ValueError: could not convert string to float: '178.7547-193.8748'
```

**Comment by blokhin** [comment]
@ansobolev

**Comment by blokhin** [comment]
```
INFO:root:/data/a0/80/8b07-f857-4429-ae70-abfcf6028d3f/_scheduler-stderr.txt unexpected CRYSTOUT parser error in /data/a0/80/8b07-f857-4429-ae70-abfcf6028d3f/_scheduler-stderr.txt:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tilde/core/api.py", line 302, in _parse
    for calc in self.Parsers[parser_name].iparse(parsable):
  File "/usr/local/lib/python3.5/dist-packages/tilde/parsers/__init__.py", line 117, in iparse
    return [cls(filename)]
  File "/usr/local/lib/python3.5/dist-packages/tilde/parsers/CRYSTAL/CRYSTAL.py", line 17, in __init__
    result = _CRYSTOUT(filename)
  File "/usr/local/lib/python3.5/dist-packages/pycrystal/output.py", line 286, in __init__
    k_v, g_v, k_r, g_r, k, g, e, v = self.get_effective_elastic_moduli()
  File "/usr/local/lib/python3.5/dist-packages/pycrystal/output.py", line 730, in get_effective_elastic_moduli
    return [float(x) for x in moduli[0].split()]
  File "/usr/local/lib/python3.5/dist-packages/pycrystal/output.py", line 730, in <listcomp>
    return [float(x) for x in moduli[0].split()]
ValueError: could not convert string to float: '-122.44-1070.00'
```

**Comment by ansobolev** [comment]
Could you give the output example for which the bug is reproduced?

**Comment by ansobolev** [comment]
Also, negative elastic moduli could themselves be the sign of erroneous calculation (they can be negative, if the structure is compressed)
